
# \u7AEF\u53E3\u53F7
server:
  port: 7301
# \u670D\u52A1\u540D\u79F0
spring:
  application:
    name: eureka-consumer01
# \u670D\u52A1\u6CE8\u518C\u4E0E\u53D1\u73B0\u76F8\u5173\u914D\u7F6E
eureka:
  client:
    # \u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
    serviceUrl:
      defaultZone: http://localhost:7101/eureka/